### ISSUE TITLE
Write counters on service stopping

### ISSUE THREAD

**Issue by amurray-thegoodpenguin** [The-Good-Penguin/tgp-krill-kounter#39]
When the system shutdown and systemd kills the service, does Krill write out its stats?

It probably should, if it doesn't then this is a feature request. If there is a way to tell SystemD that the service should be shut down late in the process, then that will help capture as many writes as possible.

**Comment by pzalewski-thegoodpenguin** [comment]
Closed by https://github.com/The-Good-Penguin/tgp-krill-kounter/pull/93
