### ISSUE TITLE
First Known Sighting Date

### ISSUE THREAD

**Issue by amurray-thegoodpenguin** [The-Good-Penguin/tgp-krill-kounter#41]
Low priority, but in the future it may be nice to include the date/time when an SD card is first seen.

This may help people to understand how long their SD card has lasted for.

**Comment by ngalea-thegoodpenguin** [comment]
I assume this can be closed?, as it has been done in:
https://github.com/The-Good-Penguin/tgp-krill-kounter/pull/99

**Comment by pzalewski-thegoodpenguin** [comment]
yup thanks
