### ISSUE TITLE
Default systemd service file has an invalid option

### ISSUE THREAD

**Issue by amurray-thegoodpenguin** [The-Good-Penguin/tgp-krill-kounter#91]
When following the README instructions, you end up with the following error:

Apr 16 18:57:27 little-machine systemd[1]: Started Start KrillKounter daemon.
Apr 16 18:57:27 little-machine KrillKounter[49110]: [main:334]: Starting app.
Apr 16 18:57:27 little-machine KrillKounter[49110]: [main:347]: option parsing failed: Unknown option -b
Apr 16 18:57:27 little-machine KrillKounter[49110]: [closeJson:36]: No JSON open

The -b option no longer exists, thus the service file should be updated.

**Comment by amurray-thegoodpenguin** [comment]
Once this issue is addressed, the default service file will attempt to use a config file that doesn't exist. As we don't provide a suitable default we should not pass in the -c config option.

**Comment by pzalewski-thegoodpenguin** [comment]
Closed by  [#92](https://github.com/The-Good-Penguin/tgp-krill-kounter/pull/92)
